# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
# https://vivien.github.io/i3blocks/
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=8

#markup=none
markup=pango
color=#2666A1
#font pango:Quicksand

[module-upgindicator]
interval=100
command=$SCRIPT_DIR/module-upgindicator
separator=true

[keyindicator]
instance=NUM
interval=once
signal=11
command=$SCRIPT_DIR/keyindicator

[keyindicator]
instance=CAPS
interval=once
signal=11
command=$SCRIPT_DIR/keyindicator

# Battery indicator
#
# The battery instance defaults to 0.
[battery]
label=[BAT
label=⚡
instance=1
interval=30

# CPU usage
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[gradient-temp]
label=CPU&#x1f321;
interval=10
instance=k10temp-pci-00c3
command=$SCRIPT_DIR/gradient-temp


[cpu_usage]
label=CPU:
min_width=57
interval=10
min_width=CPU:100%
separator=true
command=$SCRIPT_DIR/cpu_usage

# Memory usage
#
# The type defaults to "mem" if the instance is not specified.
[memory]
label=Mem:
min_width=37
separator=false
interval=30
command=$SCRIPT_DIR/memory

[memory]
label=Swp:
min_width=37
instance=mem
separator=true
interval=30

[gradient-temp]
label=GPU&#x1f321;
interval=10
instance=amdgpu-pci-0300
command=$SCRIPT_DIR/gradient-temp
# Disk usage
#
# The directory defaults to $HOME if the instance is not specified.
# The script may be called with a optional argument to set the alert
# (defaults to 10 for 10%).
[gradient-temp]
label=NVME&#x1f321;
interval=10
instance=nvme-pci-0200
command=$SCRIPT_DIR/gradient-temp

[disk]
label=/var
instance=/var
interval=30
separator=false

[disk]
label=/home
instance=/home
interval=30
separator=true

#[load_average]
#interval=10


[module-calculator]
interval=once
separator=true
command=$SCRIPT_DIR/module-calculator

[module-calendar]
interval=60
command=$SCRIPT_DIR/module-calendar

[volume]
instance=Master
min_width=57
align=center
interval=once
command=$SCRIPT_DIR/module-volume
signal=10

[module-mic]
align=center
min_width=57
interval=once
command=$SCRIPT_DIR/module-mic


# Network interface monitoring
#
# If the instance is not specified, use the interface used for default route.
# The address can be forced to IPv4 or IPv6 with -4 or -6 switches.
[iface]
instance=wlp1s0
#color=#3666A1
interval=60
separator=false
align=center
command=$SCRIPT_DIR/iface

[wifi]
instance=wlp1s0
interval=10
separator=true
align=center
command=$SCRIPT_DIR/wifi

[bandwidth]
instance=wlp1s0
min_width=75
interval=2
signal=10
align=center


