#!/usr/bin/env bash
# shellcheck source=~/bin/dotfiles_env
. ~/bin/dotfiles_env

##TODO
#- make tests to is there wallp files
#- configs
#- dirs
#- if installed pkgs

gen_nitrogen_cfg() {
    local bgconfig
    local nitrogen_cfg
    local nitrogen_cfg_file
    local bgconfig_file
    local nxin
    local file1
    local file2
    file1=$(find -L "${wallpapers_dir}" -maxdepth 1 -type f -name '*' |\
	sed 's|\.\/||gi' |\
	shuf|\
	head -n 1)
    file2=$(find -L "${wallpapers_dir}" -maxdepth 1 -type f -name '*' |\
	sed 's|\.\/||gi' |\
	shuf |\
	head -n 1)

    nitrogen_cfg_file="$nitrogen_cfg_dir/nitrogen.cfg"
    bgconfig_file="$nitrogen_cfg_dir/bg-saved.cfg"
    nxin=$(xrandr -q 2>/dev/null | awk /' connected'/'{print}' | wc -l)
    
    if [ "$nxin" = "1" ]; then
    echo "monitor n=1"
        bgconfig="[xin_0]\n"
	bgconfig="${bgconfig}file=$file1\n"
	bgconfig="${bgconfig}mode=0\n"
	bgconfig="${bgconfig}bgcolor=#000000\n\n"
    else
    echo "monitor n=1+2"
	bgconfig="[xin_0]\n"
	bgconfig="${bgconfig}file=$file1\n"
	bgconfig="${bgconfig}mode=0\n"
	bgconfig="${bgconfig}bgcolor=#000000\n\n"
	bgconfig="${bgconfig}[xin_1]\n"
	bgconfig="${bgconfig}file=$file2\n"
	bgconfig="${bgconfig}mode=0\n"
	bgconfig="${bgconfig}bgcolor=#000000"
    fi
    
    nitrogen_cfg="[geometry]\n"
    nitrogen_cfg="${nitrogen_cfg}posx=640\n"
    nitrogen_cfg="${nitrogen_cfg}posy=0\n"
    nitrogen_cfg="${nitrogen_cfg}sizex=634\n"
    nitrogen_cfg="${nitrogen_cfg}sizey=1051\n\n"
    nitrogen_cfg="${nitrogen_cfg}[nitrogen]\n"
    nitrogen_cfg="${nitrogen_cfg}view=list\n"
    nitrogen_cfg="${nitrogen_cfg}recurse=true\n"
    nitrogen_cfg="${nitrogen_cfg}sort=alpha\n"
    nitrogen_cfg="${nitrogen_cfg}icon_caps=false\n"
    nitrogen_cfg="${nitrogen_cfg}dirs=$wallpapers_dir;"
    
    if [ -f "$bgconfig_file" ]; then
	printf "[INFO] BgConfig file already created\n" 
	printf "[INFO] Backup\n"
        mv "$bgconfig_file" "${bgconfig_file}.backup" 
	printf "$bgconfig%s" > "$bgconfig_file"
	printf "[INFO] Created new %s config file\n" "$bgconfig_file"
    else
	printf "$bgconfig%s" > "$bgconfig_file"
	printf "[INFO] Created %s config file\n" "$bgconfig_file"
    fi
    
    if [ -f "$nitrogen_cfg_file" ]; then
	printf "[INFO] Nitrogen Config file already created\n" 
	printf "[INFO] Backup\n"
	mv "$nitrogen_cfg_file" "${nitrogen_cfg_file}.backup"
        printf "$nitrogen_cfg%s" > "$nitrogen_cfg_file"
	printf "[INFO] Created new %s config file\n" "$nitrogen_cfg_file"
    else
	printf "$nitrogen_cfg%s" > "$nitrogen_cfg_file"
	printf "[INFO] Created %s config file\n" "$nitrogen_cfg_file"
    fi
}

render_images() {
    local delay1
    local delay2
    local files1
    local files2
    local process_id
    local nxin 
    local nitro_opt
    local LOGS
    local DATE
    DATE="$(date +%c)"
    LOGS="$HOME/.cache/wallpapers.log"
    if [ ! -f "$LOGS" ];then
	touch "$LOGS"
    fi
    
    printf "\n%s\n" ">>> $DATE" >> "$LOGS"
    
    nitro_opt="--set-zoom-fill"
    nxin=$(xrandr -q 2>/dev/null | awk /' connected'/'{print}' | wc -l)
    nitrogen_cfg_file="$nitrogen_cfg_dir/nitrogen.cfg"
    bgconfig_file="$nitrogen_cfg_dir/bg-saved.cfg"
    if [ -d "$wallpapers_dir" ] && ! [ "$(ls -A "$wallpapers_dir")" ]
    then
	printf "[ERROR] There'nt wallpapers to render. Exiting\n" &>> "$LOGS"
	exit 1
    fi
    cd "$wallpapers_dir" || return
    delay1=1200
    delay2=600
    files1=$(find -L "${wallpapers_dir}" -maxdepth 1 -type f -name '*' | sed 's|\.\/||gi' | shuf)
    
    if [ "$nxin" = "1" ]; then
	echo "${FUNCNAME[0]}:${LINENO}:nitrogen restore head 0" &>> "$LOGS"
        nitrogen --restore --head=0 &>> "$LOGS"
    else
	echo "${FUNCNAME[0]}:${LINENO}:nitrogen restore head 0" &>> "$LOGS"
        nitrogen --restore --head=0 &>> "$LOGS"
	echo "${FUNCNAME[0]}:${LINENO}:nitrogen restore head 1" &>> "$LOGS"
        nitrogen --restore --head=1 &>> "$LOGS"
    fi

    #monitor1
    while :
    do
	for I in $files1; do
	    echo "${FUNCNAME[0]}:${LINENO}:nitrogen set wallpaper head 0" &>> "$LOGS"
	    echo "before delay"
	    nitrogen ${nitro_opt} --head=0 "$I" &>> "$LOGS"
	    sleep $delay2        
    #monitor2
	    files2=$(find "${wallpapers_dir}" -maxdepth 1 -type f -name '*' | sed 's|\.\/||gi' | shuf)
	    for J in $files2; do
		if [ "$I" == "$J" ]; then
		    continue
		else
	            echo "${FUNCNAME[0]}:${LINENO}:nitrogen set wallpaper head 1" &>> "$LOGS"
                    nitrogen ${nitro_opt} --head=1 "$J" &>> "$LOGS"
	            break
		fi
	    done
	    sleep $delay1
	    process_id=$!
	    wait $process_id
	done
    done
}
if which nitrogen &> /dev/null; then
    if [ -d "$nitrogen_cfg_dir" ]; then
	gen_nitrogen_cfg
    else
	printf "[ERROR] Can't find %s directory.\n" "$nitrogen_cfg_dir"
	printf "[INFO] Creating %s directory." "$nitrogen_cfg_dir"
	mkdir -p "$nitrogen_cfg_dir"
	printf "\r[INFO] Creating %s directory: Done\n" "$nitrogen_cfg_dir"
	gen_nitrogen_cfg
    fi
    render_images
    exit 0
else
    printf "[ERROR] Nitrogen pkg not found. Pls install pkg nitrogen\n"
    exit 1
fi
