#!/usr/bin/env bash
osys=$(cat /etc/os-release | sed -n -r '/^ID=/p' | cut -d "=" -f 2)
#APT aliases {{{
if [ "$osys" = "debian" ] || [ "$osys" = "ubuntu" ]; then
    #list dependencies
    alias pdeps="apt depends"
    #source edit
    alias src="sudo apt edit-sources"
    # update and upgrade
    alias up='sudo apt-get update'
    alias upgl='apt list -a --upgradable 2>/dev/null'
    alias upg='sudo apt-get upgrade -y'
    alias get='sudo apt-get install'
    alias remove='sudo apt-get remove --purge'
    alias upgrade-distro='sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y'
   alias fd='fdfind'
    # }}}
    # {{{ pacman alias
    #
elif [ "$osys" = "manjaro" ]; then
    # update and upgrade
    alias up='sudo pacman -Sy'
    alias upg='sudo pacman -Syu'
    alias get='sudo pacman -S'
    alias remove='sudo pacman -R'
    alias upgrade-distro='sudo pacman -Syyu'
    #alias fd='fdfind'
    
fi
# #}}}
#Neofetch {{{
alias neofetch='neofetch --block_range 0 15'
# }}}
# List directories contents aliasesc {{{
# Long form no user group, color sort by name, directories first
alias l='ls -Agophv --color=always --group-directories-first'
# Long form with user group, color sort by name, directories first
alias ll='ls -AGophv --color=always --group-directories-first'
# Order by last modified, long form no user group, color
alias lt='ls -Atogph --color=auto --group-directories-first'
# List all dirs with size
alias lv='du -h --max-depth=1 | sort -h'
# List order by type
alias lx='ls -Agxoph | grep -e "[^\/]$"'
# some more ls aliases
#show hiddens only
alias l.='ls -ApGv --group-directories-first | grep --regexp="^[.]"'
#show links only
alias li='ls -AFohL --color=always | grep --regexp="^[l]"'
#show directories
alias ld='ls -ApGoh --color=always | grep --regexp="[\/]$"'
#exa aliases
alias x='exa -alF --color=always --group-directories-first --sort name'                                 #long format no hidden
#alias xl.='exa -aF1 --sort name | grep "^[.].*[^\/]$"'                                                  # exa hidden dir, files and links
alias x.='exa -aF1 --sort name | grep "^[.]"'                                                  # exa .names
alias xt='exa -aTF -L 2 --color=always --group-directories-first --sort name'                                   # tree listing
alias xr='exa -aRlF --color=auto --color-scale --group-directories-first --level 2 --sort size -r'         #exa all directories and files, in recursive mode, inside(careful to use inside longs trees)
# grep
alias grep="grep --color=auto"
alias egrep='egrep --color=auto'
#alias to nav directories
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias CD='cd'
alias cd..="cd .."
# }}}
#Command aliases {{{
alias EXIT="exit"
alias quit="exit"
alias out="exit"
#alias cp='cp -i'
alias cp='rsync -ah --info=progress2'
# functions
#alias mv='move'
#alias rm='del'
alias tam='item_size'
alias myhost='ssh -T user@my.remote.host screen -dAr'
# IP addresses
alias ipp="dig +short myip.opendns.com @resolver1.opendns.com"

# }}}
#git {{{
#status
alias g='git status '

alias glog="git log --graph --decorate --after='1 month ago' --pretty='format:%cn commited %h on %ar. %s ;'"
#git diff
alias gdiff="git diff"
#add and rm
alias ga='git add -A'
alias gr='git restore '
#commit
alias gc='git commit'
alias gcm='git commit -m'
#push
#alias gpush='git push -u origin master'
#pull
#alias gpull='git pull'
#config
alias guser='git config --global user.name '
alias gmail='git config --global user.email '
alias gconf='git config --list --show-origin'
#push see bash_functions
#config
alias bare='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias ba='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME add -i'
alias bcm='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME commit -m'
alias b='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME status'
alias bdiff='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME diff'
alias br='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME restore'
alias bare_log="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME log --graph --decorate --after='1 month ago' --pretty='format:%cn commited %h on %ar.%s ;'"
alias bpacks='config_check packs'
alias blog='cat $HOME/.config-bkp/stage-bkp.log'
BranchHome="$(git --git-dir="$HOME/.dotfiles" --work-tree="$HOME" describe --all --exact-match HEAD | cut -d "/" -f 2 )";
if [ "$BranchHome" = "main" ]; then
    alias bs='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout testing'
else
    alias bs='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout main'
fi

# }}}
# jekyll {{{
alias jstart="bundle exec jekyll serve --livereload"
#}}}
# python {{{
alias py="python3 "
#}}}
#docker {{{
alias dstop='docker stop'
alias dup='docker-compose up'
alias dexec='docker exec -ti'
alias dcon='docker container ls -a'
alias dimg='docker image ls'
alias dstop='docker stop deb-mariadb && docker stop deb-php-apache && docker stop deb-php-phpmyadmin'
# }}}
# Shortcuts map {{{
alias fonts="fc-list"
alias down="cd ~/Downloads"
alias dow="cd ~/Downloads"
alias dwall="cd ~/.wallpapers/"
alias docs="cd ~/Documents/"
alias doc="cd ~/Documents/"
alias hd='cd /media/SamsungHDD'
alias hd2='cd /media/WDHDD'
alias hosts='sudo nvim /etc/hosts'
alias repo="cd ~/documents/projects/git"
alias dotfiles="cd ~/Documents/Projects/git/dotfiles"
alias promptrc=' $EDITOR ~/.bash/prompt'
alias profilerc='$EDITOR ~/.bash/profile'
alias aliasrc='  $EDITOR ~/.bash/aliases'
alias funcrc='   $EDITOR ~/.bash/functions'
alias pathrc='   $EDITOR ~/.bash/exports'
alias bashrc='   $EDITOR ~/.bashrc'
alias vimrc='    $EDITOR ~/.vimrc'
alias i3rc='     $EDITOR ~/.i3/config'
alias blocksrc=' $EDITOR ~/.i3/i3blocks.conf'
alias vifmrc='   $EDITOR ~/.config/vifm/vifmrc'
alias blocksdir='cd ~/.i3/i3blocks'
alias dotbash='cd ~/.bash'
# }}}
# Apps exec {{{
alias anki="cd ~/ && setsid ./Anki &>/dev/null"
alias ANKI="cd ~/ && setsid ./Anki &>/dev/null"
alias android="cd ~/ && setsid ./android-studio &>/dev/null"
alias studio="setsid studio.sh &>/dev/null"
alias ANDROID="cd ~/ && setsid ./android-studio &>/dev/null"
alias eclipse="cd ~/ && setsid ./eclipse_ide &>/dev/null"
alias ECLIPSE="cd ~/ && setsid ./eclipse_ide &>/dev/null"
alias tor="cd ~/ && setsid ./tor-browser &>/dev/null"
alias TOR="cd ~/ && setsid ./tor-browser &>/dev/null"
alias sv='sudo vim'
alias snv='sudo nvim'
alias nv='nvim'
alias v='vim'
alias cim="nvim"
alias VIM="nvim"
alias vi="vim"
alias nvi="nvim"
alias nv="nvim"
alias vifm="vifm ."
alias py="python3"
alias firefox="firefox-esr"
#alias play="vlc --play-and-exit --no-loop --no-repeat"
# }}}
alias rottenpotatoes-rails-intro="cd $HOME/Documents/Projects/git/rottenpotatoes-rails-intro"
