#!/usr/bin/env bash
for file in ~/.bash/{path,aliases,prompt,exports,functions,input,extras}; do
    [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
shopt -s autocd
shopt -s checkwinsize
shopt -s nocaseglob;
shopt -s histappend;
shopt -s cdspell;
shopt -s dotglob nullglob
for option in autocd globstar; do
    shopt -s "$option" 2> /dev/null;
done;
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
	. /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
	. /etc/bash_completion
    fi
fi
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
if which brew &> /dev/null && [ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]; then
    export BASH_COMPLETION_COMPAT_DIR="$(brew --prefix)/etc/bash_completion.d";
    source "$(brew --prefix)/etc/profile.d/bash_completion.sh";
elif [ -f /etc/bash_completion ]; then
    source /etc/bash_completion;
fi;
if type _git &> /dev/null; then
    complete -o default -o nospace -F _git g;
fi;
if [ -f ~/.git-completion.bash ]; then
    . ~/.git-completion.bash
fi
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;

complete -o "default" -o "nospace" -W "$(git --git-dir=$HOME/.dotfiles --work-tree=$HOME )" config

complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal Twitter" killall;

[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
