#!/bin/bash
#
# Based on script by z3bra -- 2014-01-21

W3MIMGDISPLAY="/usr/bin/w3m"
CATIMG="/usr/bin/catimg"
FONTH=15 # Size of one terminal row
FONTW=7 # Size of one terminal column

X=$1
Y=$2
COLUMNS=$3
LINES=$4
FILENAME=$5

#read width height <<< `echo "5;$FILENAME" | $W3MIMGDISPLAY`
#if [ -z "$width" -o -z "$height" ]; then
#    echo 'Error: Failed to obtain image size.'
#    exit 1
#fi
width=$3
heigth=$4

x=$((FONTW * X))
y=$((FONTH * Y))

max_width=$((FONTW * COLUMNS))
max_height=$((FONTH * LINES))

if [ "$width" -gt "$max_width" ]; then
    height=$((height * max_width / width))
    width=$max_width
fi
if [ "$height" -gt "$max_height" ]; then
    width=$((width * max_height / height))
    height=$max_height
fi

w3m_command="-w $width $FILENAME"

echo -e "$w3m_command" | $CATIMG 
