#!/usr/bin/env bash

# https://askubuntu.com/questions/522505/script-to-monitor-internet-connection-stability
#-q : Silence mode
#--spider : don't get, just check page availability

#dt=$(date +%Y%m%d_%H%M%S)
wget -q --tries=10 --timeout=20 --spider http://google.com

if [[ $? -eq 0 ]]; then
#    notify-send --urgency=normal "Connection" "Online!" | wall
#    STATUS="Online"
    echo "<span font='Quicksand' color='#00FF00'><b>Online</b></span>"

else
#    STATUS="Offline"
    echo "<span font='Quicksand' color='#FF0000'><b>Offline</b></span>"
fi


