#!/usr/bin/env bash

#name of monitor
SCR=$(xrandr -q 2>/dev/null | grep -w connected | cut -d " " -f1 | cut -d "-" -f1 | sed s/1//)
#process grep name
ISOPEN=`pgrep xfce4-appfinder`
case "$BLOCK_BUTTON" in
  1|2|3) 
      if [ "$ISOPEN" = "" ]; then  
        i3-msg 'exec xfce4-appfinder' >/dev/null
      else
          kill $ISOPEN
      fi
    ;;
    
            
esac
if [ "$SCR" = "Virtual" ]; then

echo "<span font='Font Awesome'color='red'> <span size='x-large'></span> </span>"
else
    echo "<span font='Font Awesome'color='red'> <span size='x-large'></span> </span>"
fi
