#!/usr/bin/env bash

source ~/bin/dotfiles_env
system_id=$(cat /etc/os-release | sed -n -r '/^ID=/p' | cut -d "=" -f 2)
opensuse="\"opensuse-tumbleweed\""

if [ "$system_id" = "debian" ] || [ "$system_id" = "ubuntu" ]; then
    check="$(expr $(apt list --upgradeable | wc -l) - 1)"
elif [ "$system_id" = "manjaro" ]; then
    check="$(checkupdates | wc -l)"
elif [ "$system_id" = "$opensuse" ]; then
    check="$(expr $(zypper list-updates | wc -l) - 3)"
fi

if [ "$check" -lt 1 ]; then
    output="<span $font_bg $green_bg $size $weight >No Updates</span>"
elif [ "$check" -gt 100 ]; then
    output="<span $font_bg $yellow_bg $size $weight >↑[+99 Pkgs]</span>"
else
    output="<span $font_bg $yellow_bg $size $weight >↑[$check Pkgs]</span>"
fi
echo "$output"
