#!/usr/bin/env bash

white_bg='     color="'#FFFFFF'" bgcolor="'#5f5f5f'"'
 red_bg='       color="'#FF0000'" bgcolor="'#5f5f5f'"'
dark_ red_bg='  color="'#f77777'" bgcolor="'#5f5f5f'"'
green_bg='     color="'#00FF00'" bgcolor="'#5f5f5f'"'
lima_green_bg_bg='color="'#C0FF00'" bgcolor="'#5f5f5f'"'
dark_green_bg_bg='color="'#418A03'" bgcolor="'#5f5f5f'"'
yellow_bg='    color="'#FFED00'" bgcolor="'#5f5f5f'"'
orange_bg='    color="'#FF5100'" bgcolor="'#5f5f5f'"'
color_off_bg=' color="'#00FF00'" bgcolor="'#5f5f5f'"'
color_on_bg='  color="'#FF0000'" bgcolor="'#FFED00'"'
white_bg_code='     "'#FFFFFF'"'
 red_bg_code='       "'#FF0000'"'
dark_ red_bg_code='  "'#BF616A'"'
green_bg_code='     "'#00FF00'"'
lima_green_bg_bg_code='"'#C0FF00'"'
dark_green_bg_bg_code='"'#418A03'"'
yellow_bg_code='    "'#FFED00'"'
orange_bg_code='    "'#FF5100'"'

# from i3_config script  
#font_bg='font="pattern from fc-list"'
font_bg="font="$(cat $HOME/bin/i3_config | awk -F'=' '/^font=/{print $2}')""


# normal bold [100; - thin 400; - normal 900; - heavy(black)]
weight='font_bg-weight="bold"'
font_bg_bold='font-weight="bold"'
font_bg_normal='font-weight="normal"'

#normal,italic
style='font_bg-style="italic"'

#none ,uppercase,lowercase,capitalize
capitalize='text-transform="capitalize"'
uppercase='text-transform="uppercase"'

# percent, xx-small , x-small , small , medium , large , x-large , xx-large , xxx-large.
size='size="100%"'
icon_size='size="100%"'

