#!/usr/bin/env bash

source ~/.i3/i3blocks/vars

TYPE="${BLOCK_INSTANCE:-caps}"

lockLine=$(xset -q | grep "Num Lock")

capsLock=$(echo "${lockLine}" | awk -F ' ' '{print $4}')
numLock=$(echo "${lockLine}" | awk -F ' ' '{print $8}')
scrollLock=$(echo "${lockLine}" | awk -F ' ' '{print $12}')

if [[ "${TYPE}" == "caps" ]]; then
  checkLock="${capsLock}"
elif [[ "${TYPE}" == "num" ]]; then
  checkLock="${numLock}"
elif [[ "${TYPE}" == "scroll" ]]; then
  checkLock="${scrollLock}"
else
  exit
fi
indicator="${checkLock}"
if [[ "${indicator}" == "on" ]]; then
    echo "<span $font $size $weight $color_on $uppercase > $BLOCK_INSTANCE </span>"
    echo "<span $font $size $weight $color_on $uppercase > $BLOCK_INSTANCE </span>"
else                                    
    echo "<span $font $size $color_off $uppercase > $BLOCK_INSTANCE </span>"
    echo "<span $font $size $color_off $uppercase > $BLOCK_INSTANCE </span>"
  
fi
