#!/usr/bin/env bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>
# Copyright (C) 2023 Bruno Franco <github@brnfra.com>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="${1:-5%}"
#------------------------------------------------------------------------
#Using pactl
pa_sink="$(pactl list short | grep output)"
pa_sink="${pa_sink:0:1}"

pa-volume() {
    #out
    pactl get-sink-volume "$pa_sink" | grep Volume | awk '{print $5}'
    vol=$(pactl get-sink-volume "$pa_sink" | grep Volume | awk '{print $5}')
    vol=${vol%\%*}
    if [[ $vol -ge 95 ]]
    then
	pactl set-sink-volume "$pa_sink" 95%
	
    fi

}

pa-mute() {
    #is mute?
    pactl get-sink-mute "$pa_sink" | cut -d ":" -f 2
}

#------------------------------------------------------------------------

capability() { # Return "Capture" if the device is a capture device
    amixer -D $MIXER get $SCONTROL |
    sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

volume() {
    amixer -D $MIXER get $SCONTROL $(capability)
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
    3) pactl set-sink-mute $pa_sink toggle ;;  # right click, mute/unmute
    4) pactl set-sink-volume $pa_sink  +${STEP}  ;; # scroll up, increase
    5) pactl set-sink-volume $pa_sink  -${STEP}  ;; # scroll down, decrease
esac

#------------------------------------------------------------------------

pm="$(pa-mute)"
pv="$(pa-volume)"
nv="${pv::-1}"

if [ $pm = "yes" ]; then
    icon="<span font='Font Awesome'  color='#88C0D0' >&#xf026; </span>"
    mute="<span font='Font Awesome' color='#BF616A'>&#xf00d; </span>"
    echo "$icon $mute"
    exit
else
    if [[ $nv -gt 95 ]]; then
	icon="<span font='Font Awesome' color='#88C0D0' size='large'>&#xf028; █</span>"
    else 
	if [[ $nv -gt 75 ]]; then
	    icon="<span font='Font Awesome' color='#88C0D0' size='large'>&#xf028; ▇</span>"
	else
	    if [[ $nv -gt 50 ]]; then
		icon="<span font='Font Awesome' color='#88C0D0' size='large'>&#xf027; ▅</span>"
	    else
		if [[ $nv -gt 25 ]]; then
		    icon="<span font='Font Awesome' color='#88C0D0' size='large'>&#xf027; ▃</span>"
		else
		    if [[ $nv -gt 0 ]]; then
			icon="<span font='Font Awesome'   color='#88C0D0' ><span size='large'>&#xf027; ▁</span></span>"
		    else
			icon="<span font='Font Awesome'  color='#88C0D0'  ><span size='large'>&#xf026;</span></span>"
		    fi #0-25
		fi #25-50
	    fi #50-75
	fi #75-99
    fi #99-100

fi #mute

echo "$icon $pv"

