#!/usr/bin/env bash
#script to check if exist upgrades avaliable
CHECK=$(expr $(apt list --upgradeable | wc -l) - 1)

if [ $CHECK -lt 1 ]; then
    exit
else
    echo "<span font='Font Awesome' color='red'>Upg! ($CHECK)</span>"
fi
