#!/usr/bin/env bash
# Arquivo: mod-battery
# Autor: Bruno Franco
# Ultima_modificacao: 26-02-2023
# Download: git@github.com:brnfra
# Licence:Este arquivo é de domínio público
# Garantia: O autor não se responsabiliza por eventuais danos
#           causados pelo uso deste arquivo.
# $ fc-list command to list fonts
font_face='"monofurNF"'
#xx-small , x-small , small , medium , large , x-large , xx-large , xxx-large.
font_size='"medium"'
font_weight='"bold"'
if [ -z "$(ls -A /sys/class/power_supply/)" ]
then
    exit 1
else
    bat_number=$(acpi -b | grep -v "unavailable" | awk '{print $2}')
    bat_number=${bat_number:0:1}
fi
status=$(acpi -b | grep "Battery $bat_number" | awk '{print $3}')
status=${status%,*}
bat_percent=$(acpi -b | grep "Battery $bat_number" | awk '{print $4}' )
bat_percent=${bat_percent%,*}
timeto=$(acpi -b | grep "Battery $bat_number" | awk '{print $5}' )
timeto=${timeto%:*}
bat_percent_int=${bat_percent%\%*}
if [ "$status" = 'Discharging' ]
then
    chrg_icon="<span "
    chrg_icon+="font=$font_face "
    chrg_icon+="color='#f44336' "
    chrg_icon+="font-weight=$font_weight "
    chrg_icon+="size=$font_size > "
    chrg_icon+='&#xf103; '
    chrg_icon+="</span>"
else
    chrg_icon="<span "
    chrg_icon+="font=$font_face "
    chrg_icon+="color='green' "
    chrg_icon+="font-weight=$font_weight "
    chrg_icon+="size=$font_size > "
    chrg_icon+='&#xf102; '
    chrg_icon+="</span>"
fi
# 0-5
if [[ 5 -ge bat_percent_int ]]
then
    btry_icon="<span "
    btry_icon+="font=$font_face "
    btry_icon+="color='red' "
    btry_icon+="size=$font_size > "
    btry_icon+='&#xf244; '
    btry_icon+="$bat_percent"
    btry_icon+="</span>"
fi
#35-6
if [[ 35 -ge bat_percent_int ]]
then
    btry_icon="<span "
    btry_icon+="font=$font_face "
    btry_icon+="color='orange' "
    btry_icon+="size=$font_size > "
    btry_icon+='&#xf243; '
    btry_icon+="$bat_percent"
    btry_icon+="</span>"
fi
#60-36
if [[ 60 -ge bat_percent_int ]] && [[ bat_percent_int -ge 36 ]]
then
    btry_icon="<span "
    btry_icon+="font=$font_face "
    btry_icon+="color='green' "
    btry_icon+="size=$font_size > "
    btry_icon+='&#xf242; '
    btry_icon+="$bat_percent"
    btry_icon+="</span>"
fi
#90-61
if [[ 90 -ge bat_percent_int ]] && [[ bat_percent_int -ge 61 ]]
then
    btry_icon="<span "
    btry_icon+="font=$font_face "
    btry_icon+="color='blue' "
    btry_icon+="size=$font_size > "
    btry_icon+='&#xf241; '
    btry_icon+="$bat_percent"
    btry_icon+="</span>"
fi
#100-91
if [[ 101 -ge bat_percent_int ]] && [[ bat_percent_int -ge 91 ]]
then
    btry_icon="<span "
    btry_icon+="font=$font_face "
    btry_icon+="color='#2666A1'"
    btry_icon+="size=$font_size > "
    btry_icon+='&#xf240; '
    btry_icon+="$bat_percent"
    btry_icon+="</span>"
fi
echo "$btry_icon" "$chrg_icon""($timeto)"
