#!/usr/bin/env bash
# Arquivo: mod-battery
# Autor: Bruno Franco
# Ultima_modificacao: 20-03-2023
# Download: git@github.com:brnfra
# Licence:Este arquivo é de domínio público
# Garantia: O autor não se responsabiliza por eventuais danos
#           causados pelo uso deste arquivo.
# $ fc-list command to list fonts
font_face='"monofurNF"'
#xx-small , x-small , small , medium , large , x-large , xx-large , xxx-large.
font_size='"medium"'
font_weight='"bold"'
icon_disch="&#xf103;"
icon_ch="&#xf102;"
icon_low="&#xf244;"
icon25="&#xf243;"
icon50="&#xf242;"
icon75="&#xf241;"
icon90="&#xf240;"
if [ -z "$(ls -A /sys/class/power_supply/)" ]
then
    exit 1
else
    bat_number=$(acpi -b | grep -v "unavailable" | awk '{print $2}')
    bat_number=${bat_number:0:1}
fi
status=$(acpi -b | grep "Battery $bat_number" | awk '{print $3}')
status=${status%,*}
bat_percent=$(acpi -b | grep "Battery $bat_number" | awk '{print $4}' )
bat_percent=${bat_percent%,*}
timeto=$(acpi -b | grep "Battery $bat_number" | awk '{print $5}' )
timeto=${timeto%:*}
bat_percent_int=${bat_percent%\%*}

if [ "$status" = 'Discharging' ]
then
    chrg_icon="<span font=$font_face color='#f44336' font-weight=$font_weight size=$font_size >$icon_disch</span>"
else
    chrg_icon="<span font=$font_face color='green' font-weight=$font_weight size=$font_size >$icon_ch</span>"
fi

if (( bat_percent_int >= 0 )) && (( bat_percent_int <= 5 ))
then
    btry_icon="<span font=$font_face color='red' size=$font_size >$icon_low $bat_percent [$timeto]</span>"
elif (( bat_percent_int >= 6 )) && (( bat_percent_int <= 35 ))
then
    btry_icon="<span font=$font_face color='orange' size=$font_size >$icon25 $bat_percent [$timeto]</span>"
elif (( bat_percent_int >= 36 )) && (( bat_percent_int <= 60 ))
then
    btry_icon="<span font=$font_face color='darkgreen' size=$font_size >$icon50 $bat_percent  [$timeto]</span>"
elif (( bat_percent_int >= 61 )) && (( bat_percent_int <= 85 ))
then
    btry_icon="<span font=$font_face color='green' size=$font_size >$icon75 $bat_percent [$timeto]</span>"
elif (( bat_percent_int >= 86 )) 
then
    btry_icon="<span font=$font_face color='#2666A1' size=$font_size >$icon90 $bat_percent [$timeto]</span>"
fi

printf "%s %s%s" "$chrg_icon" "$btry_icon" 
