#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# The second parameter overrides the mixer selection
# For PulseAudio users, use "pulse"
# For Jack/Jack2 users, use "jackplug"
# For ALSA users, you may use "default" for your primary card
# or you may use hw:# where # is the number of the card desired
MIXER="default"
[ -n "$(lsmod | grep pulse)" ] && MIXER="pulse"
[ -n "$(lsmod | grep jack)" ] && MIXER="jackplug"
MIXER="${2:-$MIXER}"

# The instance option sets the control to report and configure
# This defaults to the first control of your selected mixer
# For a list of the available, use `amixer -D $Your_Mixer scontrols`

# SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
#                   sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
#                   tail -n1
#                 )}"
SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
                  sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
                  tail -n1 
                )}"

# The first parameter sets the step to change the volume by (and units to display)
# This may be in in % or dB (eg. 5% or 3dB)
STEP="${1:-5%}"

#------------------------------------------------------------------------

capability() { # Return "Capture" if the device is a capture device
  amixer -D $MIXER get "$SCONTROL" |
    sed -n "s/  Capabilities:.*cvolume.*/Capture/p"
}

volume() {
  amixer -D $MIXER get "$SCONTROL" "$(capability)"
}

format() {
  perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?\[(on|off)\]/)'
  perl_filter+='{CORE::say $4 eq "off" ? "MUTE" : "'
  # If dB was selected, print that instead
  perl_filter+=$([[ $STEP = *dB ]] && echo '$3' || echo '$1')
  perl_filter+='"; exit}'
  perl -ne "$perl_filter"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) amixer -q -D $MIXER sset "$SCONTROL" toggle ;;  # right click, mute/unmute
  4) amixer -q -D $MIXER sset "$SCONTROL" $(capability) ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q -D $MIXER sset "$SCONTROL" $(capability) ${STEP}- unmute ;; # scroll down, decrease
esac

#------------------------------------------------------------------------
#name of monitor
SCR=$(xrandr -q 2>/dev/null | grep -w connected | cut -d " " -f1)
if [ "$SCR" = "Virtual1" ]; then

    pv="$(volume | format)"
    nv="${pv::-1}"
    icon="🔊"
    if [[ "$pv" == "MUTE" ]]; then
     icon="<span font='Font Awesome'  color='#88C0D0'  ><span size='large'>🔇 </span></span>"
        pv="<span color='#BF616A'><span size='large'>❌</span></span>"
    else
        if [[ $nv -gt 95 ]]; then
                        icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔊█</span>"
            else 
            if [[ $nv -gt 75 ]]; then
                    icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔊▇</span>"
                else
                if [[ $nv -gt 50 ]]; then
                        icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔉▅</span>"
                    else
                        if [[ $nv -gt 25 ]]; then
                            icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔉▃</span>"
                            else
                                if [[ $nv -gt 0 ]]; then
                                        icon="<span font='Font Awesome'   color='#88C0D0' ><span size='large'>🔉▁</span></span>"
                                else
                                        icon="<span font='Font Awesome'  color='#88C0D0'  ><span size='large'>🔈 </span></span>"
                                fi #0-25
                        fi #25-50
                fi #50-75
            fi #75-99
        fi #99-100

    fi #mute

    echo "$icon $pv"

else

    pv="$(volume | format)"
    nv="${pv::-1}"
    icon="🔊"
    if [[ "$pv" == "MUTE" ]]; then
     icon="<span font='Font Awesome'  color='#88C0D0'  ><span size='large'>🔇 </span></span>"
        pv="<span color='#BF616A'><span size='large'>❌</span></span>"
    else
        if [[ $nv -gt 95 ]]; then
                        icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔊█</span>"
            else 
            if [[ $nv -gt 75 ]]; then
                    icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔊▇</span>"
                else
                if [[ $nv -gt 50 ]]; then
                        icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔉▅</span>"
                    else
                        if [[ $nv -gt 25 ]]; then
                            icon="<span font='Font Awesome' color='#88C0D0' size='large'>🔉▃</span>"
                            else
                                if [[ $nv -gt 0 ]]; then
                                        icon="<span font='Font Awesome'   color='#88C0D0' ><span size='large'>🔉▁</span></span>"
                                else
                                        icon="<span font='Font Awesome'  color='#88C0D0'  ><span size='large'>🔈 </span></span>"
                                fi #0-25
                        fi #25-50
                fi #50-75
            fi #75-99
        fi #99-100

    fi #mute

    echo "$icon $pv"
fi
# icon="🔊"
# if [[ "$pv" == "MUTE" ]]; then
#     icon="<span font='Font Awesome' color='#ff4000' size='large'>🔇</span>"
#     pv="<span color='#BF616A'><span size='large'>×</span></span>"
# else
#     if [[ $nv -gt 39 ]]; then
#         icon="<span font='Font Awesome' color='#ff4000' size='large'>🔊</span>"
#     else
#         if [[ $nv -gt 0 ]]; then
#             icon="<span font='Font Awesome'   color='#ff4000' ><span size='large'>🔉</span></span>"
#         else
#             icon="<span font='Font Awesome'  color='#ff4000'  ><span size='large'>🔈</span></span>"
#         fi    This is a Java FAQ list❌🗙
#     fi
# fi

# echo "$icon  $pv"

